image: ghcr.io/vvv-school/gitpod:latest
additionalRepositories:
- url: https://github.com/robotology/icub-main
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- command: start-vnc-session.sh
